{"name": "test_uesr_err_login[admin1-123456-\\u767b\\u5f55\\u5931\\u8d25\\uff0c\\u7528\\u6237\\u540d\\u5bc6\\u7801\\u9519\\u8bef\\u6216\\u8be5\\u8d26\\u53f7\\u5df2\\u88ab\\u7981\\u7528\\uff01]", "status": "passed", "description": "\n        验证登录错误用例\n        :param username:\n        :param pwd:\n        :param excepted:\n        :return:\n        ", "attachments": [{"name": "stdout", "source": "7e9493e1-d0a0-4a7a-ae51-3c86bda2986a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'admin1'"}, {"name": "pwd", "value": "'123456'"}, {"name": "excepted", "value": "'登录失败，用户名密码错误或该账号已被禁用！'"}], "start": 1704536664763, "stop": 1704536667868, "uuid": "b4bdc86f-1262-4884-b226-5c098fda0ae8", "historyId": "0ddc0d32f6b4203dc17cb72f4252b509", "testCaseId": "89023538a1dcc1f8196c6123b4a4f5d9", "fullName": "testcases.test_err_login.TesterrUserLogin#test_uesr_err_login", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_err_login"}, {"name": "subSuite", "value": "TesterrUserLogin"}, {"name": "host", "value": "DESKTOP-4K34VI9"}, {"name": "thread", "value": "9456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_err_login"}]}