{"name": "test_uesr_err_login[admin-12121212-\\u767b\\u5f55\\u5931\\u8d25\\uff0c\\u7528\\u6237\\u540d\\u5bc6\\u7801\\u9519\\u8bef\\u6216\\u8be5\\u8d26\\u53f7\\u5df2\\u88ab\\u7981\\u7528\\uff01]", "status": "passed", "description": "\n        验证登录错误用例\n        :param username:\n        :param pwd:\n        :param excepted:\n        :return:\n        ", "attachments": [{"name": "stdout", "source": "90fe22ce-f467-4b60-acf2-f5eb79f87ae8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'admin'"}, {"name": "pwd", "value": "'12121212'"}, {"name": "excepted", "value": "'登录失败，用户名密码错误或该账号已被禁用！'"}], "start": 1704536667986, "stop": 1704536670339, "uuid": "b10065fb-10e7-4d9b-a7de-00b132b8dd13", "historyId": "d9e6e8a32f13de3429c8f361894c7eed", "testCaseId": "89023538a1dcc1f8196c6123b4a4f5d9", "fullName": "testcases.test_err_login.TesterrUserLogin#test_uesr_err_login", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_err_login"}, {"name": "subSuite", "value": "TesterrUserLogin"}, {"name": "host", "value": "DESKTOP-4K34VI9"}, {"name": "thread", "value": "9456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_err_login"}]}